spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/0ef3ca2b-0b6f-4543-b1f3-eb1e7ec2069f/v2.0
        registration:
          azure-dev:
            client-id: "poop"
            client-secret: "poop"
            provider: azure
            #client-id: externally provided
            #client-secret: externally provided
            scope:
              - openid
              - email
              - profile

using.jwt: true
